### ISSUE TITLE
Can't Install Extension

### ISSUE THREAD

**Issue by SharePointMichael** [rriverak/vscode-gitlab-explorer#4]
When I try to install the extension it fails every time.  Here is the log

8/22/2018 6:22:03 PM - Microsoft VSIX Installer
8/22/2018 6:22:03 PM - -------------------------------------------
8/22/2018 6:22:03 PM - vsixinstaller.exe version:
8/22/2018 6:22:03 PM - 15.6.152+ge95e4dd1ce
8/22/2018 6:22:03 PM - -------------------------------------------
8/22/2018 6:22:03 PM - Command line parameters:
8/22/2018 6:22:03 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\MichaelBollhoefer\Downloads\rrivera.vscode-gitlab-explorer-0.1.1.vsix
8/22/2018 6:22:03 PM - -------------------------------------------
8/22/2018 6:22:03 PM - Microsoft VSIX Installer
8/22/2018 6:22:03 PM - -------------------------------------------
8/22/2018 6:22:04 PM - Initializing Install...
8/22/2018 6:22:04 PM - Extension Details...
8/22/2018 6:22:04 PM - 	Identifier         : vscode-gitlab-explorer
8/22/2018 6:22:04 PM - 	Name               : GitLab Explorer
8/22/2018 6:22:04 PM - 	Author             : rrivera
8/22/2018 6:22:04 PM - 	Version            : 0.1.1
8/22/2018 6:22:04 PM - 	Description        : VSCode GitLab Explorer Extension to Work with GitLab Project Items like Groups, Projects, Issues etc.
8/22/2018 6:22:04 PM - 	Locale             : en-US
8/22/2018 6:22:04 PM - 	MoreInfoURL        : 
8/22/2018 6:22:04 PM - 	InstalledByMSI     : False
8/22/2018 6:22:04 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
8/22/2018 6:22:04 PM - 
8/22/2018 6:22:04 PM - 	SignatureState     : Unsigned
8/22/2018 6:22:04 PM - 	Supported Products : 
8/22/2018 6:22:04 PM - 		Microsoft.VisualStudio.Code
8/22/2018 6:22:04 PM - 			Version : 
8/22/2018 6:22:04 PM - 
8/22/2018 6:22:04 PM - 	References         : 
8/22/2018 6:22:04 PM - Signature Details...
8/22/2018 6:22:04 PM - 	Extension is not signed.
8/22/2018 6:22:04 PM - 
8/22/2018 6:22:04 PM - Searching for applicable products...
8/22/2018 6:22:04 PM - Found installed product - Global Location
8/22/2018 6:22:04 PM - Found installed product - Visual Studio Professional 2017
8/22/2018 6:22:04 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by SharePointMichael** [comment]
I got it working
